#.travis.yml

language: node_js
node_js:
  - "8.6.0"
group: "stable"
dist: "trusty"
os: "linux"
branches:
  only:
    - master
    - Development
    - Release/1.0
    
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod
